const filterOptionsData = {
  Disorder: {
    'Body Dysmorphia': false,
    'Generalized Anxiety': false,
    'Health Anxiety/Medical Phobia': {
      'Blood/Injection/Injury': false,
      'Dental Phobia': false,
    },
    Hoarding: false,
    'Obsessive Compulsive Disorder (OCD)': {
      'Aggressive/Violent': {
        'Fear of Being a Sociopath/Murderer': false,
        'Fear of a Hit-and-Run': false,
        'Fear of Self-Harm': false,
      },
      Checking: false,
      Contamination: { 'Emotional/Mental Contamination': false },
      Existential: {
        'Fear of Wasting Time': false,
      },
      'Fear of Acting on Unwanted Impulses': false,
      'Fear of Being Cancelled': false,
      'Fear of Being Misunderstood': false,
      'Fear of Contracting Sexually-Transmitted Diseases/HIV/AIDs': false,
      'Fear of Developing Other Types of OCD': false,
      'Fear of Forgetting': false,
      'Fear of Getting in Trouble': false,
      'Fear of Going Crazy': false,
      'Fear of Making the Wrong Decision': {
        'Fear of Buying the Wrong Thing': false,
      },
      'Fear of Unintentionally Causing Harm': false,
      'Magical Numbers': false,
      'Need to Know': false,
      'Not Just Right': false,
      Perfectionism: false,
      'Relationship OCD': { 'Retractive Jealousy': false },
      'Scrupulosity/Morality': {
        'Fear of Being Racist': false,
        'Fear of Sinning/Committing Blasphemy': false,
      },
      'Sexual/Gender': {
        'Fear of Being Gay/Straight': false,
        'Fear of Being Trans': false,
        'Fear of Being a Pedophile': false,
      },
      'Somatic OCD': false,
      'Symmetry/Ordering': false,
      'Fear of Uncertainty': false,
    },
    'Panic/Agoraphobia': false,
    'Specific Phobia': {
      Animals: {
        Birds: false,
        Bugs: {
          Spiders: false,
          'House Centipedes': false,
          Bees: false,
        },
        Cats: false,
        Dogs: false,
        Fish: false,
        'Mice/Rats': false,
        Sharks: false,
        Snakes: false,
      },
      Claustriphobia: false,
      Choking: false,
      Dark: false,
      Driving: false,
      Flying: false,
      Heights: false,
      'Storms/Natural Disasters': false,
      Trypophobia: false,
      'Vomit (Emetophobia)': false,
    },
    'Posttraumatic Stress Disorder (PTSD)': {
      'Combat/Military/Terrorism': false,
      'Sexual Assault': false,
      'Car Accident': false,
    },
    'Separation Anxiety': false,
    'Social Anxiety': false,
    'Trichotillomania/Excoriation': false,
  },
  Format: {
    Video: false,
    Picture: false,
    Idea: false,
    Script: false,
    Reading: false,
    Audio: false,
  },
  'Intervention Type': {
    'In Vivo': false,
  },
  Maturity: {
    Children: false,
    Adults: false,
  },
  Keyword: {},
};

export default filterOptionsData;
